// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqrFpLy42351a3xBwkOfIdZEDQPkjmLS4',
    appId: '1:852449797970:web:764a8f01e28f9ea0e07c8b',
    messagingSenderId: '852449797970',
    projectId: 'phonenumberprovider-9f35f',
    authDomain: 'phonenumberprovider-9f35f.firebaseapp.com',
    storageBucket: 'phonenumberprovider-9f35f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwnGiuh7GJV6haZ7yEPKryvmWZJeHTjFo',
    appId: '1:852449797970:android:78b722383bf0d84fe07c8b',
    messagingSenderId: '852449797970',
    projectId: 'phonenumberprovider-9f35f',
    storageBucket: 'phonenumberprovider-9f35f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOXanrZ3TMVMU7QvR6M3OVscL66pG14ig',
    appId: '1:852449797970:ios:a5caa7ad2db70ae9e07c8b',
    messagingSenderId: '852449797970',
    projectId: 'phonenumberprovider-9f35f',
    storageBucket: 'phonenumberprovider-9f35f.appspot.com',
    iosClientId: '852449797970-7uk416mq4toa1bphof2k1c32klk26o8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneuserlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOXanrZ3TMVMU7QvR6M3OVscL66pG14ig',
    appId: '1:852449797970:ios:e5e70197b109a76fe07c8b',
    messagingSenderId: '852449797970',
    projectId: 'phonenumberprovider-9f35f',
    storageBucket: 'phonenumberprovider-9f35f.appspot.com',
    iosClientId: '852449797970-e5gmqq20vh3h9orm7n1jg8ipbaa31dui.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneuserlogin.RunnerTests',
  );
}
